#!/bin/bash
source ~/venvs/tensorflow/bin/activate
echo "TEST START"

# TEST A
python sample.py -n 0 --quiet --save_dir save/horror > ./stories/A.txt 2> /dev/null
words=($(wc -w ./stories/A.txt))
if (( $words == 1 ))
then
	echo "1 A.txt = SUCCESS"
else
	echo "1 A.txt = FAILED"
fi

python sample.py -n 49 --quiet --save_dir save/horror > ./stories/A.txt 2> /dev/null
words=($(wc -w ./stories/A.txt))
if (( $words == 50 ))
then
	echo "50 A.txt = SUCCESS"
else
	echo "50 A.txt = FAILED"
fi

python sample.py -n 499 --quiet --save_dir save/horror > ./stories/A.txt 2> /dev/null
words=($(wc -w ./stories/A.txt))
if (( $words == 500 ))
then
	echo "500 A.txt = SUCCESS"
else
	echo "500 A.txt = FAILED"
fi

python sample.py -n 9999 --quiet --save_dir save/horror > ./stories/A.txt 2> /dev/null
words=($(wc -w ./stories/A.txt))
if (( $words == 10000 ))
then
	echo "10000 A.txt = SUCCESS"
else
	echo "10000 A.txt = FAILED"
fi

# TEST WORD
python sample.py -n 0 --quiet --save_dir save/horror > ./stories/WORD.txt 2> /dev/null
words=($(wc -w ./stories/WORD.txt))
if (( $words == 1 ))
then
	echo "1 WORD.txt = SUCCESS"
else
	echo "1 WORD.txt = FAILED"
fi

python sample.py -n 49 --quiet --save_dir save/horror > ./stories/WORD.txt 2> /dev/null
words=($(wc -w ./stories/WORD.txt))
if (( $words == 50 ))
then
	echo "50 WORD.txt = SUCCESS"
else
	echo "50 WORD.txt = FAILED"
fi

python sample.py -n 499 --quiet --save_dir save/horror > ./stories/WORD.txt 2> /dev/null
words=($(wc -w ./stories/WORD.txt))
if (( $words == 500 ))
then
	echo "500 WORD.txt = SUCCESS"
else
	echo "500 WORD.txt = FAILED"
fi

python sample.py -n 9999 --quiet --save_dir save/horror > ./stories/WORD.txt 2> /dev/null
words=($(wc -w ./stories/WORD.txt))
if (( $words == 10000 ))
then
	echo "10000 WORD.txt = SUCCESS"
else
	echo "10000 WORD.txt = FAILED"
fi

# TEST MULTIPLEWORDS
python sample.py -n 0 --quiet --save_dir save/horror > ./stories/MULTIPLEWORDS.txt 2> /dev/null
words=($(wc -w ./stories/MULTIPLEWORDS.txt))
if (( $words == 1 ))
then
	echo "1 MULTIPLEWORDS.txt = SUCCESS"
else
	echo "1 MULTIPLEWORDS.txt = FAILED"
fi

python sample.py -n 49 --quiet --save_dir save/horror > ./stories/MULTIPLEWORDS.txt 2> /dev/null
words=($(wc -w ./stories/MULTIPLEWORDS.txt))
if (( $words == 50 ))
then
	echo "50 MULTIPLEWORDS.txt = SUCCESS"
else
	echo "50 MULTIPLEWORDS.txt = FAILED"
fi

python sample.py -n 499 --quiet --save_dir save/horror > ./stories/MULTIPLEWORDS.txt 2> /dev/null
words=($(wc -w ./stories/MULTIPLEWORDS.txt))
if (( $words == 500 ))
then
	echo "500 MULTIPLEWORDS.txt = SUCCESS"
else
	echo "500 MULTIPLEWORDS.txt = FAILED"
fi

python sample.py -n 9999 --quiet --save_dir save/horror > ./stories/MULTIPLEWORDS.txt 2> /dev/null
words=($(wc -w ./stories/MULTIPLEWORDS.txt))
if (( $words == 10000 ))
then
	echo "10000 MULTIPLEWORDS.txt = SUCCESS"
else
	echo "10000 MULTIPLEWORDS.txt = FAILED"
fi
echo "TEST DONE"
deactivate
