#!/bin/bash

if [ $# != 2 ]
then
    echo "usage: genreWT [story] [genre]"
    exit 1
fi

cat $1 | tr " " "\n" > temp$$

cat genre/$2/* > source$$

while read word
    do
        res=$(grep -c -w "$word" source$$)
        if [ $res -eq 0 ]
        then
            echo "$word not found in $2"
            rm -f temp$$
            exit 1
        fi
    done < temp$$

rm -f temp$$
rm -f source$$
